### PR TITLE
Add bintray badge

### PR DESCRIPTION
**Pull request by jaredsburrows**
@sbosley Add bintray's badge

### CODE REVIEW

**Comment by sbosley** [comment]
Oh nice this is cool -- do you think we should make it display the latest stable version rather than the latest beta version though? When I preview the file it shows me a download link for 3.0 beta 1.

**Comment by jaredsburrows** [comment]
@sbosley Not sure. I just went here: https://bintray.com/yahoo/maven/squidb/view and clicked on the badge and it gave me the markdown.

**Comment by jaredsburrows** [comment]
@sbosley So what did you decide? I see you have a PR for 3.0 into master. We should be able to add this in.

**Comment by sbosley** [comment]
@jaredsburrows there's one thing that's still kind of weird-- after I published the 2.1.0 version, the latestVersion link went to that instead of the 3.0 beta version. It seems like it's the latest version by publication date, rather than by version number. Probably not a big deal, but it could be weird if we ever need to backport any fixes to 2.x Do you want to dig in a bit to see if it's possible to make it show the badge for the latest by version number rather than by publication date? If it turns out that's not possible it's no big deal, and we can just live with the possible occasional weirdness in that edge case.

**Comment by jaredsburrows** [comment]
@sbosley Yeah its an incremental release based on the latest uploaded artifact dates. I am guessing 3.0 will become the new release right? 2.1.0 - 3.0. So once 3.0 is out, it will say 3.0 on the badge.

**Comment by sbosley** [comment]
@jaredsburrows right, but it would revert back to showing e.g. 2.1.1 if we ever backported fixes to the 2.x branch. I guess though even in that case, we'd probably be likely to release a new 3.x build shortly thereafter, so my earlier objection is moot. Let's do it!

**Comment by jaredsburrows** [comment]
@sbosley Thanks for explaining. Sounds good!

**Pull request merged**
